version: "3.7"

services:
  hadabot_ros2_web_bridge_service:
    container_name: hadabot_ros2_web_bridge
    build:
      context: ./
      dockerfile: Dockerfile.ros2_web_bridge
    image: hadabot/ros2-web-bridge:0.2.7
    ports:
      - "9090:9090"
    networks:
      - hadabot_network
  hadabot_ros2_codeserver_service:
    container_name: hadabot_ros2_codeserver
    build:
      context: ./
      dockerfile: Dockerfile.ros2_codeserver
    image: hadabot/ros2-codeserver
    ports:
      - "9123:8080"
    volumes:
      - ../../hadabot_main:/home/hadabot/hadabot_main
    networks:
      - hadabot_network

networks:
  hadabot_network:
